import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const header = headers();
  const nextUrl = header.get("referer");
 

  const admin = nextUrl.includes("/admin");

  return (
    <html lang="en">
      <body className={inter.className}>
        {!admin && <Header />}
        {children}
      </body>
    </html>
  );
}
