import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import Navbar from "@/components/ui/Navbar";
import ScrollTop from "@/components/ui/ScrollTop";

import "@mantine/core/styles.css";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/ui/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const header = headers();
  const nextUrl = header.get("referer");
  const admin = nextUrl?.includes("/admin") ?? false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className="app">
            {!admin && <Navbar />}
            {children}
            {!admin && <ScrollTop />}
            {!admin && <Footer />}
          </main>
        </Provider>
      </body>
    </html>
  );
}
